### ISSUE TITLE
Deleting console.log(name)

### ISSUE THREAD

**Issue by sheliwaili** [learn-co-curriculum/js-if-else-files-lab#4]
when importing the other line of code into the blank file, I am following along exactly. I keep getting an error when I am told to type console.log(index.name). The error didn't change from the previous, purposeful error. I am very new, as I am sure a lot of others are, so I follow exactly. It never says to define "name" or delete console.log(name). These things are so frustrating, that I have almost quit the school 3 times. 

This was an issue following the lessons exactly, 2 lessons back, I was never told or explained to that I had to save after every single change, in order for my codes to run and not get an error.

These 2 problems have cost me more than 2 hours of trying to figure out what I am doing wrong and how to fix it.
![2017-06-22 1](https://user-images.githubusercontent.com/29619279/27458382-5116b43a-576e-11e7-9df4-6b3fb8d3cd9e.png)
![2017-06-22](https://user-images.githubusercontent.com/29619279/27458381-511487d2-576e-11e7-9b5f-51ca6df97922.png)

**Comment by gj** [comment]
Hi @sheliwaili !

I'm sorry the instructions gave you so much trouble. I've (hopefully) cleared them up a bit (https://github.com/learn-co-curriculum/js-if-else-files-lab/commit/6f8a13f0c44d79fef03abd82265d6bc2f6dbb99c) so that future students won't have the same issues.

Thank you for pointing this out!
